#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "This is a trunk based development branch"
echo "Therefore tests, linting and build must pass before pushing"
echo
echo "======== Testing (Jest) 🧪  ========"
pnpm test
echo "======== Testing ✅  ========"
echo
echo "Tested ✅ Built ✅ Pushed 🚀"
